import {
  faCheckSquare,
  faCoffee,
  faHome,
  faChevronLeft,
  faMicrophone,
  faMicrophoneAlt,
  faAssistiveListeningSystems,
  faUser,
  faPlay,
  faPause,
  faTimes,
  faSearch,
  faExclamationCircle,
  faCheckCircle,
  faChevronDown,
  faChevronRight,
  faPlusCircle,
  faBookmark,
  faHeart,
  faClock,
  faEyeSlash,
  faEye,
  faUsers,
  faPencilAlt,
  faEllipsisV,
  faCog,
  faFolder,
  faCheck,
  faLightbulb,
  faQuestionCircle,
  faDownload,
  faArrowAltCircleRight,
  faLock,
  faGlobeAmericas,
  faHeadphones,
  faMusic,
  faEnvelope,
  faSlidersH,
  faEject,
  faFileContract,
  faLongArrowAltRight,
} from '@fortawesome/free-solid-svg-icons';
import {
  faBookmark as farBookmark,
  faHeart as farHeart,
  faClock as farClock,
  faCircle,
  faTrashAlt,
} from '@fortawesome/free-regular-svg-icons';

export const iconList = {
  faQuestionCircle,
  faDownload,
  faArrowAltCircleRight,
  farBookmark,
  faUsers,
  faTrashAlt,
  faPencilAlt,
  farHeart,
  faLightbulb,
  farClock,
  faCheckSquare,
  faCoffee,
  faCheck,
  faHome,
  faChevronLeft,
  faMicrophone,
  faMicrophoneAlt,
  faAssistiveListeningSystems,
  faUser,
  faClock,
  faLock,
  faGlobeAmericas,
  faPlay,
  faPause,
  faTimes,
  faHeart,
  faHeadphones,
  faSearch,
  faBookmark,
  faExclamationCircle,
  faCheckCircle,
  faChevronDown,
  faChevronRight,
  faPlusCircle,
  faCircle,
  faEyeSlash,
  faEye,
  faEllipsisV,
  faCog,
  faFolder,
  faMusic,
  faEnvelope,
  faSlidersH,
  faEject,
  faFileContract,
  faLongArrowAltRight,
};
export type Icons = keyof typeof iconList;
